name: GitOps CD Pipeline Tf

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: kiran
    # Define environment variables at the job level for consistency
    env:
      HOME: /tmp/runner_home
      KUBECONFIG: /tmp/runner_home/.kube/config
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push Docker image
        id: build_push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Run Trivy scan on Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}
          trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME
          
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply - Create Minikube Cluster
        run: terraform apply -auto-approve -target=null_resource.minikube_cluster
        working-directory: ./terraform

      - name: Ensure kubeconfig for Minikube
        run: |
          # This step ensures the .kube directory exists and that the context is correctly set.
          # The minikube start command in the previous step should have already created the config.
          mkdir -p /tmp/runner_home/.kube
          minikube -p my-gitops-cluster update-context

      - name: Terraform Apply - Install Tools
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Update Kubernetes Manifest with new image tag
        run: |
          sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}|' manifests/my-app/deployment.yaml

      - name: Commit and Push changes to manifests
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add manifests/my-app/deployment.yaml
          git commit -m "Update application image to new build ${{ github.sha }}" || echo "No changes to commit"
          git push
